# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: ["prod"]
    pull_request:
        branches: ["prod"]
env:
    REACT_APP_MQTT_PROTOCOL: "wss"
    REACT_APP_MQTT_BROKER: mqtt.sollab.dev
    REACT_APP_MQTT_PORT: "8083"
    REACT_APP_MQTT_USERNAME: "mqtt"
    REACT_APP_MQTT_PASSWORD: "syafiq29"
jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: |
                  npm i
                  cd frontend
                  npm i
                  npm run build
            - run: |
                  cd backend
                  npm i
            - run: |
                  pm2 stop 3
                  pm2 start 3
